### ISSUE TITLE
CNN Model Predcition

### ISSUE THREAD

**Issue by aliammar182** [animikhaich/ECG-Atrial-Fibrillation-Classification-Using-CNN#1]
I am new to machine learning, can anybody tell me how to predict with any dataset after training it successfully?

**Comment by animikhaich** [comment]
3 Simple steps:
- Load the trained model
- Pass the inference data to the model in the same format as it was passed during training
- Predict on that data
- Display the output.

For further information, you can google it or take up some courses.
