### ISSUE TITLE
What is the files in Train and Test folder?

### ISSUE THREAD

**Issue by yobrepus** [animikhaich/ECG-Atrial-Fibrillation-Classification-Using-CNN#2]
In the Data_Preprocessing.ipynb, there are lines that I don't understand is you can see below

root_folder_train = 'C:\\Users\\animi\\Documents\\Dataset\\ECG Dataset\\Train\\'
root_folder_test = 'C:\\Users\\animi\\Documents\\Dataset\\ECG Dataset\\Test\\'

I saw your code show below:

samples (1).csv 7680
samples (2).csv 7680
samples.csv 7680
samples (1).csv 7680
samples (2).csv 7680
samples.csv 7680

Can you explain more how I can get those files?

**Comment by animikhaich** [comment]
I believe they have removed the dataset from the URL that I had used. 
I did find similar data from the same organization. I have not checked, but you can find it in the link: [MIT-BIH Atrial Fibrillation Database](https://physionet.org/content/afdb/1.0.0/) 
The dataset format has also changed, it is No longer in CSV format. So you may have to do some exploration regarding the same.
